apiVersion: v1
kind: Pod
metadata:
  name: challenge-hello-world-pod-{short_id}
  labels:
    chal-id: '{id}'
spec:
  automountServiceAccountToken: false
  containers:
  - name: chal
    image: 971703668052.dkr.ecr.us-east-1.amazonaws.com/challenge-registry:challenge-hello-world
    imagePullPolicy: Always
    ports:
    - containerPort: 8888
      name: service-port
    env:
    - name: FLAG
      value: {flag}
---
apiVersion: v1
kind: Service
metadata:
  name: challenge-hello-world-service-{short_id}
  labels:
    chal-id: '{id}'
spec:
  selector:
    chal-id: '{id}'
  type: NodePort
  ports:
  - name: service
    port: 8763  # doesn't really matter in this case
    targetPort: service-port
    # do not choose nodePort
